---
- name: Reserve IP
  ansible.builtin.uri:
    url: "{{ ipam_api_url }}/addresses/first_free/{{ subnet_id }}"
    method: POST
    return_content: true
    validate_certs: false
    status_code: 201
    headers: 
      token: "{{ ansible_token }}"
    body_format: json
    body:
      hostname: "{{ vm_name }}.jferre.local"
      description: "IP Reserved to {{ vm_name }}.jferre.local"
  register: new_ip
  changed_when: new_ip.json.success == true

- name: Get IP reserved
  ansible.builtin.set_fact:
    ip_reserved: "{{ new_ip.json.data }}"

- debug:
    var: ip_reserved
